import type {
  AgentPlan,
  AgentFileArtifact,
  AgentContext,
  ModelPlan,
  ServicePlan,
  ScreenPlan,
} from './types';
import { SupabaseSchemaGenerator } from './schemaGenerator';

export class MultiFileCodeGenerator {
  /**
   * Generates all required Flutter + Supabase source files according to the AgentPlan
   */
  public static generateAllFiles(plan: AgentPlan, context: AgentContext): AgentFileArtifact[] {
    const artifacts: AgentFileArtifact[] = [];

    // 1. Pubspec and config files
    artifacts.push(this.generatePubspecYaml(plan));
    artifacts.push(this.generateAnalysisOptions());

    // 2. Core architecture
    artifacts.push(this.generateAppConstants(plan, context));
    artifacts.push(this.generateAppTheme(plan));
    artifacts.push(this.generateAppRouter(plan));
    artifacts.push(this.generateFormatters());

    // 3. Reusable UI components
    artifacts.push(this.generateCustomButton(plan));
    artifacts.push(this.generateCustomTextField(plan));
    artifacts.push(this.generateLoadingIndicator(plan));
    artifacts.push(this.generateEmptyState(plan));
    artifacts.push(this.generateShimmerSkeleton());

    // 4. Data models
    for (const model of plan.models) {
      artifacts.push(this.generateModelFile(model));
    }

    // 5. Supabase services
    artifacts.push(this.generateSupabaseService());
    for (const service of plan.services) {
      if (service.name === 'SupabaseService') continue;
      artifacts.push(this.generateEntityService(service, plan));
    }

    // 6. State management providers
    artifacts.push(this.generateAppProvider(plan));

    // 7. Feature screens
    for (const screen of plan.screens) {
      artifacts.push(this.generateScreenFile(screen, plan));
    }

    // 8. App entry points
    artifacts.push(this.generateAppDart(plan));
    artifacts.push(this.generateMainDart(plan));

    // 9. Supabase migration SQL
    const migrationSql = SupabaseSchemaGenerator.generateMigrationSql(plan.schema);
    artifacts.push({
      path: 'supabase/migrations/001_initial_schema.sql',
      content: migrationSql,
      language: 'sql',
      description: 'Supabase PostgreSQL DDL and Row Level Security policies',
      isNew: true,
    });

    return artifacts;
  }

  /**
   * Parses LLM raw text output containing file codeblocks into AgentFileArtifact objects
   */
  public static parseLLMCodeArtifacts(rawText: string): AgentFileArtifact[] {
    const artifacts: AgentFileArtifact[] = [];
    const seenPaths = new Set<string>();
    const blockRegex = /```([a-zA-Z0-9_-]+)?(?:\s+filepath=["']([^"']+)["']|\s+file=["']([^"']+)["']|\s+path=["']([^"']+)["'])?([\s\S]*?)```/g;

    let match: RegExpExecArray | null;
    while ((match = blockRegex.exec(rawText)) !== null) {
      const language = (match[1] || 'dart').toLowerCase() as AgentFileArtifact['language'];
      const filePath = match[2] || match[3] || match[4];
      const content = match[5]?.trim();

      if (filePath && content) {
        // Deduplicate: keep last occurrence if same path appears twice
        if (seenPaths.has(filePath)) {
          const existingIdx = artifacts.findIndex((a) => a.path === filePath);
          if (existingIdx >= 0) {
            artifacts[existingIdx] = {
              path: filePath,
              content,
              language: language === 'sql' ? 'sql' : language === 'yaml' ? 'yaml' : 'dart',
              isNew: true,
            };
            continue;
          }
        }
        seenPaths.add(filePath);
        artifacts.push({
          path: filePath,
          content,
          language: language === 'sql' ? 'sql' : language === 'yaml' ? 'yaml' : 'dart',
          isNew: true,
        });
      }
    }

    // Detect truncation: if rawText ends mid-code-block (no closing ```)
    const lastFence = rawText.lastIndexOf('```');
    const afterLastFence = rawText.slice(lastFence + 3).trim();
    if (lastFence > 0 && afterLastFence.length > 0 && !afterLastFence.startsWith('```')) {
      // Possible truncation — the last block may be incomplete
      // Check if it looks like it was cut off (no closing fence)
      const openBlocks = (rawText.match(/```/g) || []).length;
      if (openBlocks % 2 !== 0) {
        console.warn('[Parser] Possible truncation detected — odd number of code fences');
      }
    }

    return artifacts;
  }

  private static generatePubspecYaml(plan: AgentPlan): AgentFileArtifact {
    const content = `name: ${plan.appName.toLowerCase().replace(/[^a-z0-9_]/g, '_')}
description: A production-grade Flutter application generated by FlutterForge Lovable Agent.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
`;
    return {
      path: 'pubspec.yaml',
      content,
      language: 'yaml',
      description: 'Flutter dependencies and project configuration',
      isNew: true,
    };
  }

  private static generateAnalysisOptions(): AgentFileArtifact {
    const content = `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    use_build_context_synchronously: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
`;
    return {
      path: 'analysis_options.yaml',
      content,
      language: 'yaml',
      description: 'Dart analysis and linter configuration',
      isNew: true,
    };
  }

  private static generateAppConstants(plan: AgentPlan, context: AgentContext): AgentFileArtifact {
    const supabaseUrl = context.supabaseUrl || 'https://your-project.supabase.co';
    const supabaseKey = context.supabaseAnonKey || 'your-anon-key';

    const content = `class AppConstants {
  static const String appName = '${plan.appName}';
  static const String supabaseUrl = String.fromEnvironment(
    'SUPABASE_URL',
    defaultValue: '${supabaseUrl}',
  );
  static const String supabaseAnonKey = String.fromEnvironment(
    'SUPABASE_ANON_KEY',
    defaultValue: '${supabaseKey}',
  );

  static const Duration defaultAnimationDuration = Duration(milliseconds: 300);
  static const double defaultPadding = 16.0;
  static const double defaultBorderRadius = 16.0;
}
`;
    return {
      path: 'lib/core/constants/app_constants.dart',
      content,
      language: 'dart',
      description: 'Application constants and environment variables',
      isNew: true,
    };
  }

  private static generateAppTheme(plan: AgentPlan): AgentFileArtifact {
    const pColor = plan.theme.primaryColor.replace('#', '');
    const sColor = plan.theme.secondaryColor.replace('#', '');

    const content = `import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class AppTheme {
  static const Color primary = Color(0xFF${pColor});
  static const Color secondary = Color(0xFF${sColor});
  static const Color backgroundLight = Color(0xFFF8FAFC);
  static const Color surfaceLight = Colors.white;
  static const Color textPrimaryLight = Color(0xFF0F172A);
  static const Color textSecondaryLight = Color(0xFF64748B);

  static const Color backgroundDark = Color(0xFF0F172A);
  static const Color surfaceDark = Color(0xFF1E293B);
  static const Color textPrimaryDark = Color(0xFFF8FAFC);
  static const Color textSecondaryDark = Color(0xFF94A3B8);

  static ThemeData get lightTheme {
    final base = ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      colorScheme: ColorScheme.fromSeed(
        seedColor: primary,
        secondary: secondary,
        brightness: Brightness.light,
        surface: surfaceLight,
      ),
      scaffoldBackgroundColor: backgroundLight,
    );

    return base.copyWith(
      textTheme: GoogleFonts.interTextTheme(base.textTheme),
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: false,
        iconTheme: IconThemeData(color: textPrimaryLight),
        titleTextStyle: TextStyle(
          color: textPrimaryLight,
          fontSize: 20,
          fontWeight: FontWeight.w700,
        ),
      ),
      cardTheme: CardTheme(
        color: surfaceLight,
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0xFFE2E8F0)),
        ),
      ),
    );
  }

  static ThemeData get darkTheme {
    final base = ThemeData(
      useMaterial3: true,
      brightness: Brightness.dark,
      colorScheme: ColorScheme.fromSeed(
        seedColor: primary,
        secondary: secondary,
        brightness: Brightness.dark,
        surface: surfaceDark,
      ),
      scaffoldBackgroundColor: backgroundDark,
    );

    return base.copyWith(
      textTheme: GoogleFonts.interTextTheme(base.textTheme),
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: false,
        iconTheme: IconThemeData(color: textPrimaryDark),
        titleTextStyle: TextStyle(
          color: textPrimaryDark,
          fontSize: 20,
          fontWeight: FontWeight.w700,
        ),
      ),
      cardTheme: CardTheme(
        color: surfaceDark,
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(16),
          side: const BorderSide(color: Color(0xFF334155)),
        ),
      ),
    );
  }
}
`;
    return {
      path: 'lib/core/theme/app_theme.dart',
      content,
      language: 'dart',
      description: 'Material 3 design theme with Google Fonts typography',
      isNew: true,
    };
  }

  private static generateAppRouter(plan: AgentPlan): AgentFileArtifact {
    const imports: string[] = [];
    const routes: string[] = [];

    for (const s of plan.screens) {
      imports.push(`import '../../screens/${s.name.replace('Screen', '').toLowerCase()}/${this.toSnakeCase(s.name)}.dart';`);
      routes.push(`      GoRoute(
        path: '${s.routePath}',
        name: '${s.routeName}',
        builder: (context, state) => const ${s.name}(),
      ),`);
    }

    const content = `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
${imports.join('\n')}

class AppRouter {
  static final router = GoRouter(
    initialLocation: '/splash',
    routes: [
${routes.join('\n')}
    ],
  );
}
`;
    return {
      path: 'lib/core/router/app_router.dart',
      content,
      language: 'dart',
      description: 'GoRouter declarative routing configuration',
      isNew: true,
    };
  }

  private static generateFormatters(): AgentFileArtifact {
    const content = `import 'package:intl/intl.dart';

class Formatters {
  static String formatCurrency(double amount) {
    return NumberFormat.currency(symbol: '\$', decimalDigits: 2).format(amount);
  }

  static String formatDate(DateTime? date) {
    if (date == null) return '';
    return DateFormat('MMM dd, yyyy').format(date);
  }

  static String formatTimeAgo(DateTime? date) {
    if (date == null) return '';
    final diff = DateTime.now().difference(date);
    if (diff.inDays > 7) return formatDate(date);
    if (diff.inDays > 0) return '\${diff.inDays}d ago';
    if (diff.inHours > 0) return '\${diff.inHours}h ago';
    if (diff.inMinutes > 0) return '\${diff.inMinutes}m ago';
    return 'Just now';
  }
}
`;
    return {
      path: 'lib/core/utils/formatters.dart',
      content,
      language: 'dart',
      description: 'String, currency and date formatting utilities',
      isNew: true,
    };
  }

  private static generateCustomButton(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class CustomButton extends StatelessWidget {
  final String text;
  final VoidCallback? onPressed;
  final bool isLoading;
  final bool isOutlined;
  final IconData? icon;

  const CustomButton({
    super.key,
    required this.text,
    this.onPressed,
    this.isLoading = false,
    this.isOutlined = false,
    this.icon,
  });

  @override
  Widget build(BuildContext context) {
    if (isOutlined) {
      return OutlinedButton(
        onPressed: isLoading ? null : onPressed,
        style: OutlinedButton.styleFrom(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          side: const BorderSide(color: AppTheme.primary, width: 1.5),
        ),
        child: _buildChild(context, AppTheme.primary),
      );
    }

    return ElevatedButton(
      onPressed: isLoading ? null : onPressed,
      style: ElevatedButton.styleFrom(
        backgroundColor: AppTheme.primary,
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 0,
      ),
      child: _buildChild(context, Colors.white),
    );
  }

  Widget _buildChild(BuildContext context, Color color) {
    if (isLoading) {
      return SizedBox(
        height: 20,
        width: 20,
        child: CircularProgressIndicator(strokeWidth: 2, color: color),
      );
    }
    if (icon != null) {
      return Row(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(icon, size: 18, color: color),
          const SizedBox(width: 8),
          Text(text, style: TextStyle(color: color, fontWeight: FontWeight.w600)),
        ],
      );
    }
    return Text(text, style: TextStyle(color: color, fontWeight: FontWeight.w600));
  }
}
`;
    return {
      path: 'lib/core/widgets/custom_button.dart',
      content,
      language: 'dart',
      description: 'Reusable polished primary and secondary action buttons',
      isNew: true,
    };
  }

  private static generateCustomTextField(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';

class CustomTextField extends StatelessWidget {
  final TextEditingController? controller;
  final String label;
  final String? hint;
  final IconData? prefixIcon;
  final Widget? suffixIcon;
  final bool obscureText;
  final TextInputType keyboardType;
  final String? Function(String?)? validator;
  final int maxLines;

  const CustomTextField({
    super.key,
    this.controller,
    required this.label,
    this.hint,
    this.prefixIcon,
    this.suffixIcon,
    this.obscureText = false,
    this.keyboardType = TextInputType.text,
    this.validator,
    this.maxLines = 1,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return TextFormField(
      controller: controller,
      obscureText: obscureText,
      keyboardType: keyboardType,
      validator: validator,
      maxLines: maxLines,
      decoration: InputDecoration(
        labelText: label,
        hintText: hint,
        prefixIcon: prefixIcon != null ? Icon(prefixIcon, size: 20) : null,
        suffixIcon: suffixIcon,
        filled: true,
        fillColor: isDark ? const Color(0xFF1E293B) : const Color(0xFFF1F5F9),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: theme.colorScheme.primary, width: 1.5),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      ),
    );
  }
}
`;
    return {
      path: 'lib/core/widgets/custom_text_field.dart',
      content,
      language: 'dart',
      description: 'Polished form input field with validation and icons',
      isNew: true,
    };
  }

  private static generateLoadingIndicator(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';

class LoadingIndicator extends StatelessWidget {
  final String? message;

  const LoadingIndicator({super.key, this.message});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const CircularProgressIndicator(),
          if (message != null) ...[
            const SizedBox(height: 16),
            Text(
              message!,
              style: TextStyle(
                color: Theme.of(context).textTheme.bodySmall?.color,
                fontSize: 14,
              ),
            ),
          ],
        ],
      ),
    );
  }
}
`;
    return {
      path: 'lib/core/widgets/loading_indicator.dart',
      content,
      language: 'dart',
      description: 'Centered animated loading indicator component',
      isNew: true,
    };
  }

  private static generateEmptyState(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'custom_button.dart';

class EmptyState extends StatelessWidget {
  final IconData icon;
  final String title;
  final String description;
  final String? actionText;
  final VoidCallback? onAction;

  const EmptyState({
    super.key,
    required this.icon,
    required this.title,
    required this.description,
    this.actionText,
    this.onAction,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32.0),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: theme.colorScheme.primary.withOpacity(0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, size: 48, color: theme.colorScheme.primary),
            ),
            const SizedBox(height: 20),
            Text(
              title,
              style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            Text(
              description,
              style: TextStyle(color: theme.textTheme.bodyMedium?.color?.withOpacity(0.7), fontSize: 14),
              textAlign: TextAlign.center,
            ),
            if (actionText != null && onAction != null) ...[
              const SizedBox(height: 24),
              CustomButton(text: actionText!, onPressed: onAction),
            ],
          ],
        ),
      ),
    );
  }
}
`;
    return {
      path: 'lib/core/widgets/empty_state.dart',
      content,
      language: 'dart',
      description: 'Rich empty state component with call to action',
      isNew: true,
    };
  }

  private static generateShimmerSkeleton(): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';

class ShimmerSkeleton extends StatelessWidget {
  final double width;
  final double height;
  final double borderRadius;

  const ShimmerSkeleton({
    super.key,
    this.width = double.infinity,
    required this.height,
    this.borderRadius = 12,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      width: width,
      height: height,
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1E293B) : const Color(0xFFE2E8F0),
        borderRadius: BorderRadius.circular(borderRadius),
      ),
    )
        .animate(onPlay: (controller) => controller.repeat())
        .shimmer(
          duration: 1200.ms,
          color: isDark ? const Color(0xFF334155) : const Color(0xFFF8FAFC),
        );
  }
}
`;
    return {
      path: 'lib/core/widgets/shimmer_skeleton.dart',
      content,
      language: 'dart',
      description: 'Animated skeleton loading placeholder',
      isNew: true,
    };
  }

  private static generateModelFile(model: ModelPlan): AgentFileArtifact {
    const fieldsCode = model.fields
      .map((f) => `  final ${f.dartType} ${f.name};`)
      .join('\n');

    const constructorParams = model.fields
      .map((f) => `    ${f.isNullable ? '' : 'required '}this.${f.name},`)
      .join('\n');

    const fromJsonBody = model.fields
      .map((f) => {
        if (f.dartType.includes('DateTime')) {
          return `      ${f.name}: json['${f.jsonKey}'] != null ? DateTime.parse(json['${f.jsonKey}'] as String) : null,`;
        }
        if (f.dartType.includes('double')) {
          return `      ${f.name}: (json['${f.jsonKey}'] as num?)?.toDouble() ?? 0.0,`;
        }
        if (f.dartType.includes('int')) {
          return `      ${f.name}: (json['${f.jsonKey}'] as num?)?.toInt() ?? 0,`;
        }
        if (f.dartType.includes('bool')) {
          return `      ${f.name}: json['${f.jsonKey}'] as bool? ?? false,`;
        }
        return `      ${f.name}: json['${f.jsonKey}'] as ${f.dartType}${f.isNullable ? '' : " ?? ''"},`;
      })
      .join('\n');

    const toJsonBody = model.fields
      .map((f) => {
        if (f.dartType.includes('DateTime')) {
          return `      '${f.jsonKey}': ${f.name}${f.isNullable ? '?' : ''}.toIso8601String(),`;
        }
        return `      '${f.jsonKey}': ${f.name},`;
      })
      .join('\n');

    const copyWithParams = model.fields
      .map((f) => `    ${f.dartType}? ${f.name},`)
      .join('\n');

    const copyWithBody = model.fields
      .map((f) => `      ${f.name}: ${f.name} ?? this.${f.name},`)
      .join('\n');

    const content = `class ${model.name} {
${fieldsCode}

  const ${model.name}({
${constructorParams}
  });

  factory ${model.name}.fromJson(Map<String, dynamic> json) {
    return ${model.name}(
${fromJsonBody}
    );
  }

  Map<String, dynamic> toJson() {
    return {
${toJsonBody}
    };
  }

  ${model.name} copyWith({
${copyWithParams}
  }) {
    return ${model.name}(
${copyWithBody}
    );
  }
}
`;
    return {
      path: model.filePath,
      content,
      language: 'dart',
      description: `Immutable Dart model for ${model.name}`,
      isNew: true,
    };
  }

  private static generateSupabaseService(): AgentFileArtifact {
    const content = `import 'package:supabase_flutter/supabase_flutter.dart';

class SupabaseService {
  static SupabaseClient get client => Supabase.instance.client;

  static User? get currentUser => client.auth.currentUser;
  static bool get isAuthenticated => currentUser != null;

  static Future<AuthResponse> signIn({
    required String email,
    required String password,
  }) async {
    return await client.auth.signInWithPassword(
      email: email,
      password: password,
    );
  }

  static Future<AuthResponse> signUp({
    required String email,
    required String password,
    Map<String, dynamic>? data,
  }) async {
    return await client.auth.signUp(
      email: email,
      password: password,
      data: data,
    );
  }

  static Future<void> signOut() async {
    await client.auth.signOut();
  }

  static Stream<AuthState> get authStateStream => client.auth.onAuthStateChange;
}
`;
    return {
      path: 'lib/services/supabase_service.dart',
      content,
      language: 'dart',
      description: 'Central Supabase client holder and authentication service',
      isNew: true,
    };
  }

  private static generateEntityService(service: ServicePlan, plan: AgentPlan): AgentFileArtifact {
    const entityName = service.name.replace('Service', '');
    const modelName = entityName;
    const tableName = this.toSnakeCase(entityName) + 's';
    const modelSnake = this.toSnakeCase(modelName);

    const content = `import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/${modelSnake}.dart';
import 'supabase_service.dart';

class ${service.name} {
  final SupabaseClient _client = SupabaseService.client;

  Future<List<${modelName}>> fetchAll() async {
    try {
      final response = await _client
          .from('${tableName}')
          .select('*')
          .order('created_at', ascending: false);
      return (response as List<dynamic>)
          .map((json) => ${modelName}.fromJson(json as Map<String, dynamic>))
          .toList();
    } catch (e) {
      return [];
    }
  }

  Stream<List<${modelName}>> streamAll() {
    return _client
        .from('${tableName}')
        .stream(primaryKey: ['id'])
        .order('created_at', ascending: false)
        .map((maps) => maps.map((m) => ${modelName}.fromJson(m)).toList());
  }

  Future<${modelName}?> create(${modelName} item) async {
    final response = await _client
        .from('${tableName}')
        .insert(item.toJson())
        .select()
        .single();
    return ${modelName}.fromJson(response);
  }

  Future<void> update(String id, Map<String, dynamic> data) async {
    await _client.from('${tableName}').update(data).eq('id', id);
  }

  Future<void> delete(String id) async {
    await _client.from('${tableName}').delete().eq('id', id);
  }
}
`;
    return {
      path: service.filePath,
      content,
      language: 'dart',
      description: `Supabase CRUD and Realtime service for ${modelName}`,
      isNew: true,
    };
  }

  private static generateAppProvider(plan: AgentPlan): AgentFileArtifact {
    const mainModel = plan.models.find((m) => m.name !== 'UserProfile') || plan.models[0];
    const modelName = mainModel?.name || 'Item';
    const modelSnake = this.toSnakeCase(modelName);
    const serviceName = `${modelName}Service`;

    const content = `import 'package:flutter/material.dart';
import '../models/${modelSnake}.dart';
import '../services/${this.toSnakeCase(serviceName)}.dart';
import '../services/supabase_service.dart';

class AppProvider extends ChangeNotifier {
  final ${serviceName} _service = ${serviceName}();

  List<${modelName}> _items = [];
  bool _isLoading = false;
  String? _error;

  List<${modelName}> get items => _items;
  bool get isLoading => _isLoading;
  String? get error => _error;
  bool get isAuthenticated => SupabaseService.isAuthenticated;

  AppProvider() {
    loadItems();
  }

  Future<void> loadItems() async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _items = await _service.fetchAll();
    } catch (e) {
      _error = e.toString();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> addItem(${modelName} item) async {
    try {
      final created = await _service.create(item);
      if (created != null) {
        _items.insert(0, created);
        notifyListeners();
      }
    } catch (e) {
      _error = e.toString();
      notifyListeners();
    }
  }

  Future<void> deleteItem(String id) async {
    try {
      await _service.delete(id);
      _items.removeWhere((item) => item.id == id);
      notifyListeners();
    } catch (e) {
      _error = e.toString();
      notifyListeners();
    }
  }
}
`;
    return {
      path: 'lib/state/app_provider.dart',
      content,
      language: 'dart',
      description: 'ChangeNotifier state controller for application data',
      isNew: true,
    };
  }

  private static generateScreenFile(screen: ScreenPlan, plan: AgentPlan): AgentFileArtifact {
    if (screen.routeName === 'splash') {
      return this.generateSplashScreen();
    }
    if (screen.routeName === 'auth') {
      return this.generateAuthScreen();
    }
    if (screen.routeName === 'home') {
      return this.generateHomeScreen(plan);
    }
    if (screen.routeName === 'profile') {
      return this.generateProfileScreen(plan);
    }

    // Default screen template
    const content = `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class ${screen.name} extends StatelessWidget {
  const ${screen.name}({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('${screen.name.replace('Screen', '')}'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
      ),
      body: const Center(
        child: Text('${screen.description}'),
      ),
    );
  }
}
`;
    return {
      path: screen.filePath,
      content,
      language: 'dart',
      description: `${screen.name} UI Screen`,
      isNew: true,
    };
  }

  private static generateSplashScreen(): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../services/supabase_service.dart';
import '../../core/theme/app_theme.dart';

class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> with SingleTickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this, duration: const Duration(milliseconds: 800));
    _fadeAnimation = CurvedAnimation(parent: _controller, curve: Curves.easeIn);
    _controller.forward();
    _checkAuth();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _checkAuth() async {
    try {
      await Supabase.initialize(url: AppConstants.supabaseUrl, anonKey: AppConstants.supabaseAnonKey);
    } catch (e) {
      // Handle initialization error
    }
    if (!mounted) return;
    final session = Supabase.instance.client.auth.currentSession;
    if (session != null) {
      context.go('/');
    } else {
      context.go('/auth');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FadeTransition(
          opacity: _fadeAnimation,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: AppTheme.primary.withOpacity(0.1),
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.bolt, size: 64, color: AppTheme.primary),
              ),
            const SizedBox(height: 24),
            const CircularProgressIndicator(),
          ],
        ),
      ),
    );
  }
}
`;
    return {
      path: 'lib/screens/splash/splash_screen.dart',
      content,
      language: 'dart',
      description: 'Animated splash screen and auth status router',
      isNew: true,
    };
  }

  private static generateAuthScreen(): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../services/supabase_service.dart';
import '../../core/widgets/custom_button.dart';
import '../../core/widgets/custom_text_field.dart';
import '../../core/theme/app_theme.dart';

class AuthScreen extends StatefulWidget {
  const AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  bool _isSignUp = false;
  bool _isLoading = false;
  String? _errorMessage;

  Future<void> _handleSubmit() async {
    final email = _emailController.text.trim();
    final password = _passwordController.text.trim();

    if (email.isEmpty || password.isEmpty) {
      setState(() => _errorMessage = 'Please fill in all fields');
      return;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      if (_isSignUp) {
        await SupabaseService.signUp(email: email, password: password);
      } else {
        await SupabaseService.signIn(email: email, password: password);
      }
      if (mounted) context.go('/');
    } catch (e) {
      setState(() => _errorMessage = e.toString());
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Icon(Icons.lock_outline, size: 48, color: AppTheme.primary),
                const SizedBox(height: 16),
                Text(
                  _isSignUp ? 'Create an Account' : 'Welcome Back',
                  style: const TextStyle(fontSize: 26, fontWeight: FontWeight.bold),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 8),
                Text(
                  _isSignUp ? 'Sign up with Supabase' : 'Sign in to continue',
                  style: const TextStyle(color: Colors.grey),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 32),
                if (_errorMessage != null) ...[
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: Colors.red.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(_errorMessage!, style: const TextStyle(color: Colors.red)),
                  ),
                  const SizedBox(height: 16),
                ],
                CustomTextField(
                  controller: _emailController,
                  label: 'Email',
                  prefixIcon: Icons.email_outlined,
                  keyboardType: TextInputType.emailAddress,
                ),
                const SizedBox(height: 16),
                CustomTextField(
                  controller: _passwordController,
                  label: 'Password',
                  prefixIcon: Icons.lock_outline,
                  obscureText: true,
                ),
                const SizedBox(height: 24),
                CustomButton(
                  text: _isSignUp ? 'Sign Up' : 'Sign In',
                  isLoading: _isLoading,
                  onPressed: _handleSubmit,
                ),
                const SizedBox(height: 16),
                TextButton(
                  onPressed: () => setState(() => _isSignUp = !_isSignUp),
                  child: Text(_isSignUp ? 'Already have an account? Sign In' : "Don't have an account? Sign Up"),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
`;
    return {
      path: 'lib/screens/auth/auth_screen.dart',
      content,
      language: 'dart',
      description: 'Supabase Authentication login and registration screen',
      isNew: true,
    };
  }

  private static generateHomeScreen(plan: AgentPlan): AgentFileArtifact {
    const mainModel = plan.models.find((m) => m.name !== 'UserProfile') || plan.models[0];
    const modelName = mainModel?.name || 'Item';
    const titleField = mainModel?.fields?.find((f) => f.name === 'title' || f.jsonKey === 'title');
    const titleAccessor = titleField ? `item.${titleField.name}` : `'Item \${index + 1}'`;
    const descField = mainModel?.fields?.find((f) => f.name === 'description' || f.jsonKey === 'description');
    const descAccessor = descField ? `item.${descField.name}` : `'No description'`;
    const idAccessor = mainModel?.fields?.find((f) => f.name === 'id') ? `item.${mainModel!.fields.find((f) => f.name === 'id')!.name}` : 'index';

    const content = `import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../state/app_provider.dart';
import '../../core/widgets/empty_state.dart';
import '../../core/widgets/loading_indicator.dart';
import '../../core/theme/app_theme.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final provider = context.watch<AppProvider>();

    return Scaffold(
      appBar: AppBar(
        title: const Text('${plan.appName}'),
        actions: [
          IconButton(
            icon: const Icon(Icons.person_outline),
            onPressed: () => context.push('/profile'),
          ),
        ],
      ),
      body: provider.isLoading
          ? _buildShimmerList()
          : provider.items.isEmpty
              ? EmptyState(
                  icon: Icons.layers_outlined,
                  title: 'No ${modelName}s Found',
                  description: 'Get started by creating your first ${modelName.toLowerCase()} in Supabase.',
                  actionText: 'Refresh',
                  onAction: () => provider.loadItems(),
                )
              : RefreshIndicator(
                  onRefresh: () => provider.loadItems(),
                  child: ListView.separated(
                    padding: const EdgeInsets.all(16),
                    itemCount: provider.items.length,
                    separatorBuilder: (_, __) => const SizedBox(height: 12),
                    itemBuilder: (context, index) {
                      final item = provider.items[index];
                      return Card(
                        elevation: 0,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                          side: BorderSide(color: Theme.of(context).colorScheme.outlineVariant.withOpacity(0.3)),
                        ),
                        child: ListTile(
                          contentPadding: const EdgeInsets.all(16),
                          leading: CircleAvatar(
                            backgroundColor: AppTheme.primary.withOpacity(0.1),
                            child: const Icon(Icons.star, color: AppTheme.primary),
                          ),
                          title: Text(
                            ${titleAccessor},
                            style: const TextStyle(fontWeight: FontWeight.bold),
                          ),
                          subtitle: Text(
                            ${descAccessor},
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                          trailing: const Icon(Icons.chevron_right),
                          onTap: () => context.push('/detail/${idAccessor}'),
                        ),
                      ).animate().fadeIn(delay: Duration(milliseconds: 50 * index), duration: 300.ms).slideY(begin: 0.05);
                    },
                  ),
                ),
    );
  }

  Widget _buildShimmerList() {
    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: 6,
      itemBuilder: (context, index) => Padding(
        padding: const EdgeInsets.only(bottom: 12),
        child: Card(
          elevation: 0,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          child: ListTile(
            contentPadding: const EdgeInsets.all(16),
            leading: CircleAvatar(backgroundColor: Colors.grey.shade200),
            title: Container(height: 16, width: 120, color: Colors.grey.shade200),
            subtitle: Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Container(height: 12, width: 200, color: Colors.grey.shade100),
            ),
          ),
        ),
      ),
    );
  }
}
`;
    return {
      path: 'lib/screens/home/home_screen.dart',
      content,
      language: 'dart',
      description: 'Main dashboard with dynamic Supabase entity list',
      isNew: true,
    };
  }

  private static generateProfileScreen(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../services/supabase_service.dart';
import '../../core/widgets/custom_button.dart';
import '../../core/theme/app_theme.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final user = SupabaseService.currentUser;

    return Scaffold(
      appBar: AppBar(title: const Text('Profile')),
      body: ListView(
        padding: const EdgeInsets.all(24),
        children: [
          Center(
            child: CircleAvatar(
              radius: 48,
              backgroundColor: AppTheme.primary.withOpacity(0.1),
              child: const Icon(Icons.person, size: 48, color: AppTheme.primary),
            ),
          ),
          const SizedBox(height: 16),
          Text(
            user?.email ?? 'user@example.com',
            style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 32),
          ListTile(
            leading: const Icon(Icons.security),
            title: const Text('Account Security'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () {},
          ),
          ListTile(
            leading: const Icon(Icons.notifications_outlined),
            title: const Text('Notifications'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () {},
          ),
          const SizedBox(height: 32),
          CustomButton(
            text: 'Sign Out',
            isOutlined: true,
            icon: Icons.logout,
            onPressed: () async {
              await SupabaseService.signOut();
              if (context.mounted) context.go('/auth');
            },
          ),
        ],
      ),
    );
  }
}
`;
    return {
      path: 'lib/screens/profile/profile_screen.dart',
      content,
      language: 'dart',
      description: 'Profile and user settings screen',
      isNew: true,
    };
  }

  private static generateAppDart(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'core/theme/app_theme.dart';
import 'core/router/app_router.dart';
import 'state/app_provider.dart';

class ${this.toPascalCase(plan.appName)}App extends StatelessWidget {
  const ${this.toPascalCase(plan.appName)}App({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AppProvider()),
      ],
      child: MaterialApp.router(
        title: '${plan.appName}',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: ThemeMode.system,
        routerConfig: AppRouter.router,
      ),
    );
  }
}
`;
    return {
      path: 'lib/app.dart',
      content,
      language: 'dart',
      description: 'Main App widget with MultiProvider and GoRouter',
      isNew: true,
    };
  }

  private static generateMainDart(plan: AgentPlan): AgentFileArtifact {
    const content = `import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/constants/app_constants.dart';
import 'app.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Supabase Client
  await Supabase.initialize(
    url: AppConstants.supabaseUrl,
    anonKey: AppConstants.supabaseAnonKey,
  );

  runApp(const ${this.toPascalCase(plan.appName)}App());
}
`;
    return {
      path: 'lib/main.dart',
      content,
      language: 'dart',
      description: 'Application entry point initializing Supabase',
      isNew: true,
    };
  }

  private static toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
      .replace(/^[a-z]/, (chr) => chr.toUpperCase());
  }

  private static toSnakeCase(str: string): string {
    return str
      .replace(/([A-Z])/g, '_$1')
      .toLowerCase()
      .replace(/^_/, '');
  }
}
